# Site settings
title: Hélène M.
email: your-email@domain.com
description: "Hélène Marcombes - Maquetiste / Assistante D.A."
baseurl: ""
url: "http://bookhelenem.fr"
permalink: /:categories/:title

pygments: true
github: [Repository metadata]

# Build settings
markdown: kramdown
permalink: pretty

baseurl: /bookhelenem

exclude: ['node_modules']
