# Site settings
title: Hélène M.
email: your-email@domain.com
description: "Hélène Marcombes - Maquetiste / Assistante D.A."
baseurl: ""
url: "http://bookhelenem.fr"
permalink: /:categories/:title

# Build settings
markdown: kramdown
permalink: pretty


exclude: ['node_modules']
