# Site settings
title: Hélène M.
email: helenemarcombes@gmail.com
description: "Graphiste / Maquettiste / Éxécutante"
baseurl: "/bookhelenem"
url: "http://bookhelenem.fr"
permalink: none

pygments: true
github: [Repository metadata]

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['node_modules']
